/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import BUS.NhanVienBUS;
import DAO.Connect;
import DAO.NhanVienDAO;
import DTO.NhanVienDTO;
import static java.nio.file.Files.list;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import static java.util.Collections.list;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;





/**
 *
 * @author Admin
 */

public class NhanVien extends javax.swing.JFrame {
    private ArrayList<NhanVienDTO> dsnv;
    DefaultTableModel model;
    
    public NhanVien() {
        initComponents();
        Load();

        this.setLocationRelativeTo(null);
        dsnv = new NhanVienDAO().docDSNV();
        model = (DefaultTableModel) tbNV.getModel();

        model.setColumnIdentifiers(new Object[]{
           "Mã Nhân Viên", "Tên Nhân Viên", "Năm Sinh", "Số Điện Thoại"
        });
        DefaultTableModel tableModel = (DefaultTableModel) tbNV.getModel();
           tableModel.setRowCount(0);
        
           
        showTable();// hien thi thong tin trong danh sach
    }

    public void showTable() {
        for (NhanVienDTO nv : dsnv) {
            model.addRow(new Object[]{
               i++, nv.getTENNV(), nv.getNAMSINH(), nv.getSDT()
            });
        }
    }
    
    
    

public void Load(){
    tbNV.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
                @Override
                public void valueChanged(ListSelectionEvent e){
                    if(tbNV.getSelectedRow() >= 0){
                    txtMANV.setText(tbNV.getValueAt(tbNV.getSelectedRow(), 0) + "");
                    txtTENNV.setText(tbNV.getValueAt(tbNV.getSelectedRow(), 1) + "");
                    txtNAMSINH.setText(tbNV.getValueAt(tbNV.getSelectedRow(), 2) + "");
                    txtSDT.setText(tbNV.getValueAt(tbNV.getSelectedRow(), 3) + "");
                    }
                }
            });
    
} 
//    public void loadData(){
//        try {
//            Connect a = new Connect();
//            Connection conn = a.getConnection();
//            int number;
//            Vector row,column;
//            column = new Vector();
//            Statement st = conn.createStatement();
//            ResultSet rs = st.executeQuery("Select * from NVIEN");
//            ResultSetMetaData metadata = rs.getMetaData();
//            number = metadata.getColumnCount(); // tra ve so cot
//            
//            for(int i = 1;i <= number;i++) {
//                column.add(metadata.getColumnName(i)); // lay ra tieu de cua cac cot
//            }
//           tbn.setColumnIdentifiers(column);
//           
//           while(rs.next()) {
//               row = new Vector();
//               for(int i =1; i<= number;i++){
//                   row.addElement(rs.getString(i));
//               }
//               tbn.addRow(row);
//               tbNV.setModel(tbn);
//           }
//        }catch(Exception ex) {
//            System.out.println(ex.toString());
//        }
//    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        txtMANV = new javax.swing.JTextField();
        txtNAMSINH = new javax.swing.JTextField();
        btnThemNV = new javax.swing.JButton();
        btnXoaNV = new javax.swing.JButton();
        btnSuaNV = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNV = new javax.swing.JTable();
        txtTENNV = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Họ Tên :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Năm Sinh :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("SĐT :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Mã Nhân Viên :");

        txtMANV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMANVActionPerformed(evt);
            }
        });

        btnThemNV.setText("Thêm");
        btnThemNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNVActionPerformed(evt);
            }
        });

        btnXoaNV.setText("Xóa");
        btnXoaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNVActionPerformed(evt);
            }
        });

        btnSuaNV.setText("Sửa");
        btnSuaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaNVActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("NHÂN VIÊN");

        tbNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma nhan vien", "Ten nhan vien", "Nam sinh", "So dien thoai"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbNV.setToolTipText("");
        tbNV.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbNVAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                tbNVAncestorRemoved(evt);
            }
        });
        jScrollPane1.setViewportView(tbNV);

        txtTENNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTENNVActionPerformed(evt);
            }
        });

        jButton1.setText("Trang chủ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnThemNV, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, Short.MAX_VALUE)
                .addComponent(btnSuaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215)
                .addComponent(btnXoaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(273, 273, 273)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)))
                            .addComponent(jLabel4))
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSDT, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                            .addComponent(txtMANV)
                            .addComponent(txtNAMSINH)
                            .addComponent(txtTENNV))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMANV, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTENNV, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNAMSINH, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemNV, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNVActionPerformed
//        // TODO add your handling code here:
//        try {
//            Connect a = new Connect();
//            Connection conn =a.getConnection();
//            PreparedStatement ps = conn.prepareStatement("insert into Student value(?,?,?,?)");
//            ps.setString(1, txtMANV.getText());
//            ps.setString(2, txtTENNV.getText());
//            ps.setInt(3, Integer.parseInt(txtNAMSINH.getText()));
//            ps.setString(4, txtSDT.getText());
//           
//        }catch(Exception ex) {
//            System.out.println(ex.toString());
//        }


        
      
        NhanVienDTO nv =new NhanVienDTO();
        nv.setMANV(Integer.parseInt(txtMANV.getText()));
        nv.setTENNV(txtTENNV.getText());
        nv.setNAMSINH(Integer.parseInt(txtNAMSINH.getText()));
        nv.setSDT(txtSDT.getText());
            
        
        if(new NhanVienDAO().addNhanVienDTO(nv)){
            JOptionPane.showMessageDialog(rootPane, "Thêm thành công!");
            dsnv.add(nv); // them vao danh sach SV
        } else{
            JOptionPane.showMessageDialog(rootPane, "Mã số sinh viên không được trùng lặp!");
        }
        
        showResult();
        
        String qry = "INSERT INTO NVIEN(MANV,TENNV,NAMSINH,SDT) values(" + "'" + txtMANV.getText() + "'" + "," + "'" + txtTENNV.getText() + "'" + "," + "'" + txtNAMSINH.getText() + "'" + "," + "'" + txtSDT.getText() + "'" + ")";
        System.out.println(qry);
        Connect conn = new Connect();
        System.out.println(qry);
        try{

            try(Statement st = conn.conn.createStatement()){
                st.executeUpdate(qry);
            }
        }
        catch(SQLException e){
            System.out.println(e.getMessage());
        }
        
        
        new NhanVien().setVisible(true);
        this.dispose();
        
       
    }//GEN-LAST:event_btnThemNVActionPerformed

    private void tbNVAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbNVAncestorAdded
//        // TODO add your handling code here:
//         tbNV.setModel(new javax.swing.table.DefaultTableModel(
//            new Object [][] {
//
//            },
//            new String [] {
//                "MANV", "TENNV", "NAMSINH", "SDT"
//            }
//        ) {
//            boolean[] canEdit = new boolean [] {
//                false, false, true, false
//            };
//
//            public boolean isCellEditable(int rowIndex, int columnIndex) {
//                return canEdit [columnIndex];
//            }
//        });
    }//GEN-LAST:event_tbNVAncestorAdded

    private void txtMANVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMANVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMANVActionPerformed

    private void txtTENNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTENNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTENNVActionPerformed

    private void tbNVAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbNVAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tbNVAncestorRemoved

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
  //       TODO add your handling code here:
//        NhanVienBUS bus = new NhanVienBUS();
//        if (NhanVienBUS.dsnv == null) {
//            try {
//                bus.docDSNV();
//            } catch (Exception ex) {
//                Logger.getLogger(NhanVien.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }
//        Vector header = new Vector();
//        header.add("Mã Nhân Viên");
//        header.add("Tên Nhân Viên");
//        header.add("Năm Sinh");
//        header.add("Số điện thoại");
//        model = new DefaultTableModel(header, 0);
//        for (NhanVienDTO nv : NhanVienBUS.dsnv) {
//            Vector row = new Vector();
//            row.add(nv.MANV);
//            row.add(nv.TENNV);
//            row.add(nv.NAMSINH);
//            row.add(nv.SDT);
//
//            model.addRow(row);
//        }
//        tbNV.setModel(model);
//        
//        
     
        
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new QuanLy().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSuaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaNVActionPerformed
        // TODO add your handling code here:
        int i = tbNV.getSelectedRow();
                int selectedID = (int) tbNV.getValueAt(i, 0);
                if(i >= 0){
                                String qry = "UPDATE NVIEN SET MANV= " + "'" + txtMANV.getText() + "'" + ", TENNV=" +"N"+ "'" + txtTENNV.getText() + "'" + ", NAMSINH=" + "'" + txtNAMSINH.getText() + "'" + ", SDT=" + "'" + txtSDT.getText() + "'" + " WHERE MANV=" + selectedID;
                                System.out.println(qry);
                                model.removeRow(i);

                                Connect conn = new Connect();
                            try{

                                try(Statement st = conn.conn.createStatement()){
                                    st.executeUpdate(qry);
                                    }
                                }

                            catch(SQLException e){
                                System.out.println(e.getMessage());
                                                  }
                        }
                Load();
//                new NhanVien().setVisible(true);
//                this.dispose();
    }//GEN-LAST:event_btnSuaNVActionPerformed

    private void btnXoaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNVActionPerformed
        // TODO add your handling code here:

            
            
        int i = tbNV.getSelectedRow();
                int selectedID = (int) tbNV.getValueAt(i, 0);
                if(i >= 0){
                                String qry = "DELETE FROM NVIEN WHERE MANV=" + selectedID;
                                System.out.println(qry);
                                model.removeRow(i);

                                Connect conn = new Connect();
                            try{

                                try(Statement st = conn.conn.createStatement()){
                                    st.executeUpdate(qry);
                                    }
                                }

                            catch(SQLException e){
                                System.out.println(e.getMessage());
                                                  }
                        }
    }//GEN-LAST:event_btnXoaNVActionPerformed

   int i = 1;

    public void showResult() {
        NhanVienDTO nv = dsnv.get(dsnv.size() - 1);
        model.addRow(new Object[]{
             i++, nv.getTENNV(), nv.getNAMSINH(), nv.getSDT()
        });
    }              

//private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {                                        
//        // TODO add your handling code here:
//        
//        String MANV = txtMANV.getText();
//       
//        String TENNV = txtTENNV.getText();
//        int NAMSINH = Integer.parseInt(txtNAMSINH.getText());
//        String SDT = txtSDT.getText();
//        
//        NhanVien NVIEN = new NhanVien(MANV, TENNV, NAMSINH, SDT);
//        
//        NhanVien.insert(NVIEN);
//        
//        showNhanVien();
//    }       
           
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaNV;
    private javax.swing.JButton btnThemNV;
    private javax.swing.JButton btnXoaNV;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbNV;
    private javax.swing.JTextField txtMANV;
    private javax.swing.JTextField txtNAMSINH;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTENNV;
    // End of variables declaration//GEN-END:variables
}
